#ifndef _IDT_H
#define _IDT_H
//******************************************************************************
//*
//*  @file		idt.h
//*  @author    Abdul Rafay (abdul.rafay@lums.edu.pk)
//*  @brief		Contains the definitions and functions to setup the Interrupt 
//*             Descriptor Table (IDT) for the x86 architecture. The IDT is 
//*             used by the CPU to determine how to handle interrupts and 
//*             exceptions.
//*  @version	0.1
//*
//*****************************************************************************/
//-----------------------------------------------------------------------------
// 		REQUIRED HEADERS
//-----------------------------------------------------------------------------

#include <stdint.h>

//-----------------------------------------------------------------------------
// 		PUBLIC INTERFACE DEFINES/TYPES
//-----------------------------------------------------------------------------

/***  Macros for IDT Gate types  ***/

//! Task gate (offset unused)
#define IDT_GATE_TYPE_TASK       0x5

//! 16-bit interrupt gate
#define IDT_GATE_TYPE_16_INT     0x6

//! 16-bit trap gate
#define IDT_GATE_TYPE_16_TRAP    0x7

//! 32-bit interrupt gate
#define IDT_GATE_TYPE_32_INT     0xE

//! 32-bit trap gate
#define IDT_GATE_TYPE_32_TRAP    0xF

/***  Macros for IDT Gate attributes  ***/

//! Gate is present (annd valid)
#define IDT_ATTR_PRESENT        0x80

//! For memory protection bits
#define IDT_ATTR_DPL0           0x00  //! DPL 0 (highest privilege)
#define IDT_ATTR_DPL1           0x20  //! DPL 1
#define IDT_ATTR_DPL2           0x40  //! DPL 2
#define IDT_ATTR_DPL3           0x60  //! DPL 3 (lowest privilege)

//-----------------------------------------------------------------------------
// 		PUBLIC INTERFACE DATA STRUCTURES
//-----------------------------------------------------------------------------

/*******************************************************************************
 * 
 *  @struct  idt_entry_t
 *  @brief   Represents a single entry in the Interrupt Descriptor Table (IDT). 
 *           Each entry corresponds to an interrupt or exception handler, and 
 *           is called a "gate".
 *	
******************************************************************************/
typedef struct {

    //! lower 16 bits of the ISR address
    uint16_t        offset_low;

    //! specifies the 16 bit segment selector from the GDT to use
    uint16_t        selector;

    //! reserved 8 bits, must be zero
    uint8_t         zero;

    //! upper 4 bits for flags, and lower 4 bits for gate type
    //! Gate type can be: 
    //! 0x5 (task gate [offset unused]), 0x6 (16 bit interrupt gate)
    //! 0x7 (16 bit trap gate), 0xE (32 bit interrupt gate), or
    //! 0xF (32 bit trap gate)
    //! 4 bit of flags: `[P, DPL1, DPL0, always 0]`
    //! DPL represents the Descriptor Privilege Level, which is used to
    //! determine the privilege level allowed to access the gate. Note that
    //! this mechanism is only used by interrupts generated by the `int`
    //! instruction, and not used by hardware interrupts.
    uint8_t         gate_type_attr;

    //! higher 16 bits of the ISR address
    uint16_t        offset_high;
    
} __attribute__((packed)) idt_entry_t;


/*******************************************************************************
 * 
 *   @struct    idt_ptr_t
 *   @brief     Represents the 48-bit pointer to the IDT in memory. This 
 *              structure is used to load the IDT into the CPU's IDTR register.
 *   @note      The IDT pointer structure contains the size of the IDT in bytes
 * 
 ******************************************************************************/
typedef struct {

    //! Size of the IDT in bytes
    uint16_t            limit;

    //! Base address of the IDT
    uint32_t            base;

} __attribute__((packed)) idt_ptr_t;

//-----------------------------------------------------------------------------
// 		INTERFACE PROTOTYPES
//-----------------------------------------------------------------------------

/*******************************************************************************
 * 
 *   @function  idt_init
 *   @brief     Initializes the Interrupt Descriptor Table (IDT) with the 
 *              standard CPU exceptions and interrupts. Expects the PIC to be 
 *              pre-mapped to correct offsets.
 * 
*******************************************************************************/
void idt_init ();

/*******************************************************************************
 * 
 *   @function  get_idt_ptr
 *   @brief     Returns a pointer to the IDT pointer structure, which contains
 *              the size and base address of the IDT in memory.
 * 
*******************************************************************************/
idt_ptr_t* get_idt_ptr ();


/*******************************************************************************
 * 
 *   @function  load_init
 *   @brief     Loads the IDT into the CPU's IDTR register.
 * 
*******************************************************************************/
void load_idt (uint32_t);

#endif // _IDT_H